language: php
php:
  - '7.0'
  - '7.1'

services:
  - postgresql

postgres:
  adapter: postgresql
  database: students_test
  username: postgres

before_script:
  - composer install
  - "psql -c 'create database students_test;' -U postgres"

script:
  - vendor/bin/phpunit --debug -v
